[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
onebrc-lib = { path = "./onebrc-lib" }


[profile.release]
debug = true

[[bench]]
name = "obrc"
harness = false
